spring:
    datasource:
        name: dclog
        url: jdbc:oracle:thin:@192.168.2.220:1521:xe
        username: dclog
        password: dc2015
        # HikariDataSource
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver
        filters: stat
        maxActive: 1
        initialSize: 1
        maxWait: 60000
        minIdle: 0
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x' FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    aop:
      auto: true

#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: com.duplicall.model
